// <auto-generated />
namespace Performance.Logger.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class durationchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(durationchange));
        
        string IMigrationMetadata.Id
        {
            get { return "201609141545551_duration change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
