// <auto-generated />
namespace Test.Performance.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initialcreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialcreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201609050540332_Initial creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
